  <link href="{{ asset('css/admin/animate.css') }}" rel="stylesheet">
  <link href="{{ asset('css/admin/sky-mega-menu.css') }}" rel="stylesheet">
  <link href="{{ asset('css/admin/sky-mega-menu-black.css') }}" rel="stylesheet">
  <link href="{{ asset('css/admin/sky-tabs.css') }}" rel="stylesheet">
  <link href="{{ asset('css/admin/sky-tabs-black.css') }}" rel="stylesheet">
  <link href="{{ asset('css/admin/toastr.css') }}" rel="stylesheet">
  <link href="{{ asset('css/admin/summernote.css') }}" rel="stylesheet">
  <link href="{{ asset('css/admin/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('css/admin/style.css') }}" rel="stylesheet">
  <link href="{{ asset('css/admin/font-awesome/css/font-awesome.css') }}" rel="stylesheet">